### ISSUE TITLE
Disable more flakey tests

### ISSUE THREAD

**Issue by ash211** [palantir/spark#112]
Flaked in https://circleci.com/gh/palantir/spark/424:
- `org.apache.spark.util.collection.ExternalSorterSuite`
  -  `- cleanup of intermediate files in shuffle with failures *** FAILED *** (96 milliseconds)`
- `org.apache.spark.sql.kafka010.KafkaSourceStressForDontFailOnDataLossSuite`
  - `- stress test for failOnDataLoss=false *** FAILED *** (1 minute, 11 seconds)`

Flaked in https://circleci.com/gh/palantir/spark/425:
- `org.apache.spark.sql.kafka010.KafkaSourceStressForDontFailOnDataLossSuite`
  - `- stress test for failOnDataLoss=false *** FAILED *** (1 minute, 13 seconds)`

**Comment by ash211** [comment]
Flaked in https://circleci.com/gh/palantir/spark/448#artifacts/containers/0

`BlockManagerReplicationSuite.scala`:
```
 5432 [info] - proactive block replication - 2 replicas - 1 block manager deletions (736 milliseconds)
 5433 [info] - proactive block replication - 3 replicas - 2 block manager deletions (933 milliseconds)
 5434 [info] - proactive block replication - 4 replicas - 3 block manager deletions (1 second, 305 milliseconds)
 5435 [info] - proactive block replication - 5 replicas - 4 block manager deletions *** FAILED *** (1 second, 739 milliseconds)
 5436 [info]   4 did not equal 5 (BlockManagerReplicationSuite.scala:497)
 5437 [info]   org.scalatest.exceptions.TestFailedException:
 5438 [info]   at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:500)
 5439 [info]   at org.scalatest.FunSuite.newAssertionFailedException(FunSuite.scala:1555)
 5440 [info]   at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:466)
 5441 [info]   at org.apache.spark.storage.BlockManagerProactiveReplicationSuite.testProactiveReplication(BlockManagerReplicationSuite.scala:497)
```

Flaked for @robert3005 locally:

- `org.apache.spark.sql.hive.thriftserver.CliSuite`

**Comment by robert3005** [comment]
Also
```
[info] SparkListenerWithClusterSuite:
[info] - SparkListener sends executor added message *** FAILED *** (2 seconds, 923 milliseconds)
[info]   java.util.NoSuchElementException: key not found: 0
[info]   at scala.collection.MapLike$class.default(MapLike.scala:228)
[info]   at scala.collection.AbstractMap.default(Map.scala:59)
[info]   at scala.collection.mutable.HashMap.apply(HashMap.scala:65)
[info]   at org.apache.spark.scheduler.SparkListenerWithClusterSuite$$anonfun$2.apply$mcV$sp(SparkListenerWithClusterSuite.scala:55)
[info]   at org.apache.spark.scheduler.SparkListenerWithClusterSuite$$anonfun$2.apply(SparkListenerWithClusterSuite.scala:40)
[info]   at org.apache.spark.scheduler.SparkListenerWithClusterSuite$$anonfun$2.apply(SparkListenerWithClusterSuite.scala:40)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
[info]   at org.apache.spark.SparkFunSuite.withFixture(SparkFunSuite.scala:68)
[info]   at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163)
[info]   at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
[info]   at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175)
[info]   at org.apache.spark.scheduler.SparkListenerWithClusterSuite.org$scalatest$BeforeAndAfterEach$$super$runTest(SparkListenerWithClusterSuite.scala:30)
[info]   at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:255)
[info]   at org.apache.spark.scheduler.SparkListenerWithClusterSuite.org$scalatest$BeforeAndAfter$$super$runTest(SparkListenerWithClusterSuite.scala:30)
[info]   at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200)
[info]   at org.apache.spark.scheduler.SparkListenerWithClusterSuite.runTest(SparkListenerWithClusterSuite.scala:30)
[info]   at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
[info]   at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]   at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208)
[info]   at org.scalatest.FunSuite.runTests(FunSuite.scala:1555)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1424)
[info]   at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1555)
[info]   at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
[info]   at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]   at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212)
[info]   at org.apache.spark.SparkFunSuite.org$scalatest$BeforeAndAfterAll$$super$run(SparkFunSuite.scala:31)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
[info]   at org.apache.spark.scheduler.SparkListenerWithClusterSuite.org$scalatest$BeforeAndAfter$$super$run(SparkListenerWithClusterSuite.scala:30)
[info]   at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241)
[info]   at org.apache.spark.scheduler.SparkListenerWithClusterSuite.run(SparkListenerWithClusterSuite.scala:30)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:357)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:502)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:296)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:286)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
```
