### ISSUE TITLE
Upgrade xbean-asm7-shaded to 4.15 to support Java 14

### ISSUE THREAD

**Issue by pkoenig10** [palantir/spark#696]
Currently using Java 14 results in the following error:
```
java.lang.IllegalArgumentException: Unsupported class file major version 58
	at org.apache.xbean.asm7.ClassReader.<init>(ClassReader.java:184)
	at org.apache.xbean.asm7.ClassReader.<init>(ClassReader.java:166)
	at org.apache.xbean.asm7.ClassReader.<init>(ClassReader.java:152)
	at org.apache.xbean.asm7.ClassReader.<init>(ClassReader.java:273)
	at org.apache.spark.util.ClosureCleaner$.getClassReader(ClosureCleaner.scala:49)
	at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:516)
	at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:499)
```

This upgrade has already merged upstream.
- https://github.com/apache/spark/commit/f93460dae96d3668919b31d10d409c7b5033e267
- https://github.com/apache/spark/commit/ea0e119f84036aa7bf4f99d397217862c730f7e5
- https://github.com/apache/spark/commit/1ac6bd9f7929e7b907a0c2262e42b4d8a24ebbaa

**Comment by pkoenig10** [comment]
@rshkv

**Comment by rshkv** [comment]
Thank you for pointing this out and finding those commits. Opened a PR here #697.
